### ISSUE TITLE
Training with cscc dataset, model not optimized properly

### ISSUE THREAD

**Issue by henryccl** [biomed-AI/Hist2ST#4]
Hello, thank you for sharing this interesting work, I'm having some issues running this code to reproduce the results in the article and would appreciate it if you could take the time to help me out.

Specifically, when training the cscc dataset, the model's weight values always become nan after a few STEPS of training (roughly 4-6 STEPS), which further leads to the model's outputs and loss values becoming nan when computed.I checked the input data and found that they do not carry nan, so the model weights should gradually become nan during the optimization process.

I suspected that the learning rate was too large, so I tried to turn it down (1e-5 --> 1e-7), but it still didn't solve the problem.

Note that the code and dataset used were downloaded from the link provided by this project, and the training was done with the default parameters.

I tried to use the cscc model weights you provided to infer cscc samples and found that I can infer properly and the results are correct. Also I can successfully train and infer about her2st dataset with this code. So I think the baseline code and data provided by this project should be correct. But why am I unable to train the cscc data?

The gpu used is 4090 and the exact output is as follows:

```
/home/anaconda3/envs/hist2st/bin/python3.9 /home/Hist2ST/HIST2ST_train.py
/home/anaconda3/envs/hist2st/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: /home/anaconda3/envs/hist2st/lib/python3.9/site-packages/torchvision/image.so: undefined symbol: _ZNK3c1010TensorImpl36is_contiguous_nondefault_policy_implENS_12MemoryFormatE
  warn(f"Failed to load image Python extension: {e}")
[easydl] tensorflow not available!
['P5_ST_rep1']
Loading imgs...
Loading metadata...
['P5_ST_rep1']
Loading imgs...
Loading metadata...
3-hist2ST_cscc_zinb_bake-5-7-2-8-4-16-32output_log-0.25-5-0.5-mean-4
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name            | Type       | Params
-----------------------------------------------
0 | patch_embedding | Conv2d     | 4.7 K
1 | x_embed         | Embedding  | 65.5 K
2 | y_embed         | Embedding  | 65.5 K
3 | vit             | ViT        | 71.4 M
4 | mean            | Sequential | 175 K
5 | disp            | Sequential | 175 K
6 | pi              | Sequential | 175 K
7 | coef            | Sequential | 1.1 M
8 | gene_head       | Sequential | 177 K
-----------------------------------------------
73.3 M    Trainable params
0         Non-trainable params
73.3 M    Total params
293.090   Total estimated model params size (MB)
Epoch 0:   0%|          | 0/11 [00:00<?, ?it/s] loss: tensor(1.6666, device='cuda:0', grad_fn=<AddBackward0>)
Epoch 0:   9%|▉         | 1/11 [00:00<00:02,  4.44it/s, v_num=29, mse_loss_step=1.410, bake_loss_step=0.000151, zinb_loss_step=1.020]loss: tensor(2.1415, device='cuda:0', grad_fn=<AddBackward0>)
Epoch 0:  18%|█▊        | 2/11 [00:00<00:01,  5.12it/s, v_num=29, mse_loss_step=1.680, bake_loss_step=0.000142, zinb_loss_step=1.850]loss: tensor(1.9952, device='cuda:0', grad_fn=<AddBackward0>)
Epoch 0:  27%|██▋       | 3/11 [00:00<00:01,  5.34it/s, v_num=29, mse_loss_step=1.580, bake_loss_step=0.000132, zinb_loss_step=1.660]loss: tensor(1.4243, device='cuda:0', grad_fn=<AddBackward0>)
Epoch 0:  36%|███▋      | 4/11 [00:00<00:01,  5.72it/s, v_num=29, mse_loss_step=1.230, bake_loss_step=0.000135, zinb_loss_step=0.787]loss: tensor(1.4509, device='cuda:0', grad_fn=<AddBackward0>)
Epoch 0:  45%|████▌     | 5/11 [00:00<00:00,  6.15it/s, v_num=29, mse_loss_step=1.220, bake_loss_step=0.000128, zinb_loss_step=0.920]loss: tensor(nan, device='cuda:0', grad_fn=<AddBackward0>)
Epoch 0:  55%|█████▍    | 6/11 [00:01<00:00,  5.16it/s, v_num=29, mse_loss_step=nan.0, bake_loss_step=nan.0, zinb_loss_step=nan.0]   loss: tensor(nan, device='cuda:0', grad_fn=<AddBackward0>)
Epoch 0:  64%|██████▎   | 7/11 [00:01<00:00,  4.68it/s, v_num=29, mse_loss_step=nan.0, bake_loss_step=nan.0, zinb_loss_step=nan.0]loss: tensor(nan, device='cuda:0', grad_fn=<AddBackward0>)
Epoch 0:  73%|███████▎  | 8/11 [00:01<00:00,  4.44it/s, v_num=29, mse_loss_step=nan.0, bake_loss_step=nan.0, zinb_loss_step=nan.0]loss: tensor(nan, device='cuda:0', grad_fn=<AddBackward0>)
Epoch 0:  82%|████████▏ | 9/11 [00:01<00:00,  4.63it/s, v_num=29, mse_loss_step=nan.0, bake_loss_step=nan.0, zinb_loss_step=nan.0]loss: tensor(nan, device='cuda:0', grad_fn=<AddBackward0>)
Epoch 0:  91%|█████████ | 10/11 [00:02<00:00,  4.81it/s, v_num=29, mse_loss_step=nan.0, bake_loss_step=nan.0, zinb_loss_step=nan.0]loss: tensor(nan, device='cuda:0', grad_fn=<AddBackward0>)
Epoch 1:   0%|          | 0/11 [00:00<?, ?it/s, v_num=29, mse_loss_step=nan.0, bake_loss_step=nan.0, zinb_loss_step=nan.0, mse_loss_epoch=nan.0, bake_loss_epoch=nan.0, zinb_loss_epoch=nan.0]loss: tensor(nan, device='cuda:0', grad_fn=<AddBackward0>)
Epoch 1:   9%|▉         | 1/11 [00:00<00:01,  6.82it/s, v_num=29, mse_loss_step=nan.0, bake_loss_step=nan.0, zinb_loss_step=nan.0, mse_loss_epoch=nan.0, bake_loss_epoch=nan.0, zinb_loss_epoch=nan.0]loss: tensor(nan, device='cuda:0', grad_fn=<AddBackward0>)
Epoch 1:  18%|█▊        | 2/11 [00:00<00:01,  6.81it/s, v_num=29, mse_loss_step=nan.0, bake_loss_step=nan.0, zinb_loss_step=nan.0, mse_loss_epoch=nan.0, bake_loss_epoch=nan.0, zinb_loss_epoch=nan.0]loss: tensor(nan, device='cuda:0', grad_fn=<AddBackward0>)
Epoch 1:  27%|██▋       | 3/11 [00:00<00:01,  7.13it/s, v_num=29, mse_loss_step=nan.0, bake_loss_step=nan.0, zinb_loss_step=nan.0, mse_loss_epoch=nan.0, bake_loss_epoch=nan.0, zinb_loss_epoch=nan.0]loss: tensor(nan, device='cuda:0', grad_fn=<AddBackward0>)
Epoch 1:  36%|███▋      | 4/11 [00:00<00:00,  7.31it/s, v_num=29, mse_loss_step=nan.0, bake_loss_step=nan.0, zinb_loss_step=nan.0, mse_loss_epoch=nan.0, bake_loss_epoch=nan.0, zinb_loss_epoch=nan.0]loss: tensor(nan, device='cuda:0', grad_fn=<AddBackward0>)
Epoch 1:  45%|████▌     | 5/11 [00:00<00:00,  7.15it/s, v_num=29, mse_loss_step=nan.0, bake_loss_step=nan.0, zinb_loss_step=nan.0, mse_loss_epoch=nan.0, bake_loss_epoch=nan.0, zinb_loss_epoch=nan.0]loss: tensor(nan, device='cuda:0', grad_fn=<AddBackward0>)
Epoch 1:  55%|█████▍    | 6/11 [00:00<00:00,  6.07it/s, v_num=29, mse_loss_step=nan.0, bake_loss_step=nan.0, zinb_loss_step=nan.0, mse_loss_epoch=nan.0, bake_loss_epoch=nan.0, zinb_loss_epoch=nan.0]loss: tensor(nan, device='cuda:0', grad_fn=<AddBackward0>)
Epoch 1:  64%|██████▎   | 7/11 [00:01<00:00,  5.43it/s, v_num=29, mse_loss_step=nan.0, bake_loss_step=nan.0, zinb_loss_step=nan.0, mse_loss_epoch=nan.0, bake_loss_epoch=nan.0, zinb_loss_epoch=nan.0]loss: tensor(nan, device='cuda:0', grad_fn=<AddBackward0>)
Epoch 1:  73%|███████▎  | 8/11 [00:01<00:00,  5.68it/s, v_num=29, mse_loss_step=nan.0, bake_loss_step=nan.0, zinb_loss_step=nan.0, mse_loss_epoch=nan.0, bake_loss_epoch=nan.0, zinb_loss_epoch=nan.0]loss: tensor(nan, device='cuda:0', grad_fn=<AddBackward0>)
Epoch 1:  82%|████████▏ | 9/11 [00:01<00:00,  5.95it/s, v_num=29, mse_loss_step=nan.0, bake_loss_step=nan.0, zinb_loss_step=nan.0, mse_loss_epoch=nan.0, bake_loss_epoch=nan.0, zinb_loss_epoch=nan.0]loss: tensor(nan, device='cuda:0', grad_fn=<AddBackward0>)
Epoch 1:  91%|█████████ | 10/11 [00:01<00:00,  6.01it/s, v_num=29, mse_loss_step=nan.0, bake_loss_step=nan.0, zinb_loss_step=nan.0, mse_loss_epoch=nan.0, bake_loss_epoch=nan.0, zinb_loss_epoch=nan.0]loss: tensor(nan, device='cuda:0', grad_fn=<AddBackward0>)
Epoch 1: 100%|██████████| 11/11 [00:01<00:00,  5.56it/s, v_num=29, mse_loss_step=nan.0, bake_loss_step=nan.0, zinb_loss_step=nan.0, mse_loss_epoch=nan.0, bake_loss_epoch=nan.0, zinb_loss_epoch=nan.0]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation:   0%|          | 0/1 [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/1 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/aaa/User/bbb/Hist2ST/HIST2ST_train.py", line 102, in <module>
    trainer.fit(model, train_loader, test_loader)
  File "/home/aaa/anaconda3/envs/hist2st/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 545, in fit
    call._call_and_handle_interrupt(
  File "/home/aaa/anaconda3/envs/hist2st/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/aaa/anaconda3/envs/hist2st/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 581, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/aaa/anaconda3/envs/hist2st/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 990, in _run
    results = self._run_stage()
  File "/home/aaa/anaconda3/envs/hist2st/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1036, in _run_stage
    self.fit_loop.run()
  File "/home/aaa/anaconda3/envs/hist2st/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py", line 202, in run
    self.advance()
  File "/home/aaa/anaconda3/envs/hist2st/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py", line 359, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/home/aaa/anaconda3/envs/hist2st/lib/python3.9/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 137, in run
    self.on_advance_end(data_fetcher)
  File "/home/aaa/anaconda3/envs/hist2st/lib/python3.9/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 285, in on_advance_end
    self.val_loop.run()
  File "/home/aaa/anaconda3/envs/hist2st/lib/python3.9/site-packages/pytorch_lightning/loops/utilities.py", line 181, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/home/aaa/anaconda3/envs/hist2st/lib/python3.9/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 134, in run
    self._evaluation_step(batch, batch_idx, dataloader_idx, dataloader_iter)
  File "/home/aaa/anaconda3/envs/hist2st/lib/python3.9/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 391, in _evaluation_step
    output = call._call_strategy_hook(trainer, hook_name, *step_args)
  File "/home/aaa/anaconda3/envs/hist2st/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 309, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/aaa/anaconda3/envs/hist2st/lib/python3.9/site-packages/pytorch_lightning/strategies/strategy.py", line 403, in validation_step
    return self.lightning_module.validation_step(*args, **kwargs)
  File "/home/aaa/User/bbb/Hist2ST/HIST2ST.py", line 254, in validation_step
    r.append(pearsonr(pred[g], exp[g])[0])
  File "/home/aaa/anaconda3/envs/hist2st/lib/python3.9/site-packages/scipy/stats/_stats_py.py", line 4837, in pearsonr
    normxm = linalg.norm(xm)
  File "/home/aaa/anaconda3/envs/hist2st/lib/python3.9/site-packages/scipy/linalg/_misc.py", line 146, in norm
    a = np.asarray_chkfinite(a)
  File "/home/aaa/anaconda3/envs/hist2st/lib/python3.9/site-packages/numpy/lib/function_base.py", line 630, in asarray_chkfinite
    raise ValueError(
ValueError: array must not contain infs or NaNs
Epoch 1: 100%|██████████| 11/11 [00:02<00:00,  4.33it/s, v_num=29, mse_loss_step=nan.0, bake_loss_step=nan.0, zinb_loss_step=nan.0, mse_loss_epoch=nan.0, bake_loss_epoch=nan.0, zinb_loss_epoch=nan.0]


进程已结束,退出代码1

```

**Comment by franzt7788** [comment]
> Hello, thank you for sharing this interesting work, I'm having some issues running this code to reproduce the results in the article and would appreciate it if you could take the time to help me out.
> 
> Specifically, when training the cscc dataset, the model's weight values always become nan after a few STEPS of training (roughly 4-6 STEPS), which further leads to the model's outputs and loss values becoming nan when computed.I checked the input data and found that they do not carry nan, so the model weights should gradually become nan during the optimization process.
> 
> I suspected that the learning rate was too large, so I tried to turn it down (1e-5 --> 1e-7), but it still didn't solve the problem.
> 
> Note that the code and dataset used were downloaded from the link provided by this project, and the training was done with the default parameters.
> 
> I tried to use the cscc model weights you provided to infer cscc samples and found that I can infer properly and the results are correct. Also I can successfully train and infer about her2st dataset with this code. So I think the baseline code and data provided by this project should be correct. But why am I unable to train the cscc data?
> 
> The gpu used is 4090 and the exact output is as follows:
> 
> ```
> /home/anaconda3/envs/hist2st/bin/python3.9 /home/Hist2ST/HIST2ST_train.py
> /home/anaconda3/envs/hist2st/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: /home/anaconda3/envs/hist2st/lib/python3.9/site-packages/torchvision/image.so: undefined symbol: _ZNK3c1010TensorImpl36is_contiguous_nondefault_policy_implENS_12MemoryFormatE
>   warn(f"Failed to load image Python extension: {e}")
> [easydl] tensorflow not available!
> ['P5_ST_rep1']
> Loading imgs...
> Loading metadata...
> ['P5_ST_rep1']
> Loading imgs...
> Loading metadata...
> 3-hist2ST_cscc_zinb_bake-5-7-2-8-4-16-32output_log-0.25-5-0.5-mean-4
> GPU available: True (cuda), used: True
> TPU available: False, using: 0 TPU cores
> IPU available: False, using: 0 IPUs
> HPU available: False, using: 0 HPUs
> LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
> 
>   | Name            | Type       | Params
> -----------------------------------------------
> 0 | patch_embedding | Conv2d     | 4.7 K
> 1 | x_embed         | Embedding  | 65.5 K
> 2 | y_embed         | Embedding  | 65.5 K
> 3 | vit             | ViT        | 71.4 M
> 4 | mean            | Sequential | 175 K
> 5 | disp            | Sequential | 175 K
> 6 | pi              | Sequential | 175 K
> 7 | coef            | Sequential | 1.1 M
> 8 | gene_head       | Sequential | 177 K
> -----------------------------------------------
> 73.3 M    Trainable params
> 0         Non-trainable params
> 73.3 M    Total params
> 293.090   Total estimated model params size (MB)
> Epoch 0:   0%|          | 0/11 [00:00<?, ?it/s] loss: tensor(1.6666, device='cuda:0', grad_fn=<AddBackward0>)
> Epoch 0:   9%|▉         | 1/11 [00:00<00:02,  4.44it/s, v_num=29, mse_loss_step=1.410, bake_loss_step=0.000151, zinb_loss_step=1.020]loss: tensor(2.1415, device='cuda:0', grad_fn=<AddBackward0>)
> Epoch 0:  18%|█▊        | 2/11 [00:00<00:01,  5.12it/s, v_num=29, mse_loss_step=1.680, bake_loss_step=0.000142, zinb_loss_step=1.850]loss: tensor(1.9952, device='cuda:0', grad_fn=<AddBackward0>)
> Epoch 0:  27%|██▋       | 3/11 [00:00<00:01,  5.34it/s, v_num=29, mse_loss_step=1.580, bake_loss_step=0.000132, zinb_loss_step=1.660]loss: tensor(1.4243, device='cuda:0', grad_fn=<AddBackward0>)
> Epoch 0:  36%|███▋      | 4/11 [00:00<00:01,  5.72it/s, v_num=29, mse_loss_step=1.230, bake_loss_step=0.000135, zinb_loss_step=0.787]loss: tensor(1.4509, device='cuda:0', grad_fn=<AddBackward0>)
> Epoch 0:  45%|████▌     | 5/11 [00:00<00:00,  6.15it/s, v_num=29, mse_loss_step=1.220, bake_loss_step=0.000128, zinb_loss_step=0.920]loss: tensor(nan, device='cuda:0', grad_fn=<AddBackward0>)
> Epoch 0:  55%|█████▍    | 6/11 [00:01<00:00,  5.16it/s, v_num=29, mse_loss_step=nan.0, bake_loss_step=nan.0, zinb_loss_step=nan.0]   loss: tensor(nan, device='cuda:0', grad_fn=<AddBackward0>)
> Epoch 0:  64%|██████▎   | 7/11 [00:01<00:00,  4.68it/s, v_num=29, mse_loss_step=nan.0, bake_loss_step=nan.0, zinb_loss_step=nan.0]loss: tensor(nan, device='cuda:0', grad_fn=<AddBackward0>)
> Epoch 0:  73%|███████▎  | 8/11 [00:01<00:00,  4.44it/s, v_num=29, mse_loss_step=nan.0, bake_loss_step=nan.0, zinb_loss_step=nan.0]loss: tensor(nan, device='cuda:0', grad_fn=<AddBackward0>)
> Epoch 0:  82%|████████▏ | 9/11 [00:01<00:00,  4.63it/s, v_num=29, mse_loss_step=nan.0, bake_loss_step=nan.0, zinb_loss_step=nan.0]loss: tensor(nan, device='cuda:0', grad_fn=<AddBackward0>)
> Epoch 0:  91%|█████████ | 10/11 [00:02<00:00,  4.81it/s, v_num=29, mse_loss_step=nan.0, bake_loss_step=nan.0, zinb_loss_step=nan.0]loss: tensor(nan, device='cuda:0', grad_fn=<AddBackward0>)
> Epoch 1:   0%|          | 0/11 [00:00<?, ?it/s, v_num=29, mse_loss_step=nan.0, bake_loss_step=nan.0, zinb_loss_step=nan.0, mse_loss_epoch=nan.0, bake_loss_epoch=nan.0, zinb_loss_epoch=nan.0]loss: tensor(nan, device='cuda:0', grad_fn=<AddBackward0>)
> Epoch 1:   9%|▉         | 1/11 [00:00<00:01,  6.82it/s, v_num=29, mse_loss_step=nan.0, bake_loss_step=nan.0, zinb_loss_step=nan.0, mse_loss_epoch=nan.0, bake_loss_epoch=nan.0, zinb_loss_epoch=nan.0]loss: tensor(nan, device='cuda:0', grad_fn=<AddBackward0>)
> Epoch 1:  18%|█▊        | 2/11 [00:00<00:01,  6.81it/s, v_num=29, mse_loss_step=nan.0, bake_loss_step=nan.0, zinb_loss_step=nan.0, mse_loss_epoch=nan.0, bake_loss_epoch=nan.0, zinb_loss_epoch=nan.0]loss: tensor(nan, device='cuda:0', grad_fn=<AddBackward0>)
> Epoch 1:  27%|██▋       | 3/11 [00:00<00:01,  7.13it/s, v_num=29, mse_loss_step=nan.0, bake_loss_step=nan.0, zinb_loss_step=nan.0, mse_loss_epoch=nan.0, bake_loss_epoch=nan.0, zinb_loss_epoch=nan.0]loss: tensor(nan, device='cuda:0', grad_fn=<AddBackward0>)
> Epoch 1:  36%|███▋      | 4/11 [00:00<00:00,  7.31it/s, v_num=29, mse_loss_step=nan.0, bake_loss_step=nan.0, zinb_loss_step=nan.0, mse_loss_epoch=nan.0, bake_loss_epoch=nan.0, zinb_loss_epoch=nan.0]loss: tensor(nan, device='cuda:0', grad_fn=<AddBackward0>)
> Epoch 1:  45%|████▌     | 5/11 [00:00<00:00,  7.15it/s, v_num=29, mse_loss_step=nan.0, bake_loss_step=nan.0, zinb_loss_step=nan.0, mse_loss_epoch=nan.0, bake_loss_epoch=nan.0, zinb_loss_epoch=nan.0]loss: tensor(nan, device='cuda:0', grad_fn=<AddBackward0>)
> Epoch 1:  55%|█████▍    | 6/11 [00:00<00:00,  6.07it/s, v_num=29, mse_loss_step=nan.0, bake_loss_step=nan.0, zinb_loss_step=nan.0, mse_loss_epoch=nan.0, bake_loss_epoch=nan.0, zinb_loss_epoch=nan.0]loss: tensor(nan, device='cuda:0', grad_fn=<AddBackward0>)
> Epoch 1:  64%|██████▎   | 7/11 [00:01<00:00,  5.43it/s, v_num=29, mse_loss_step=nan.0, bake_loss_step=nan.0, zinb_loss_step=nan.0, mse_loss_epoch=nan.0, bake_loss_epoch=nan.0, zinb_loss_epoch=nan.0]loss: tensor(nan, device='cuda:0', grad_fn=<AddBackward0>)
> Epoch 1:  73%|███████▎  | 8/11 [00:01<00:00,  5.68it/s, v_num=29, mse_loss_step=nan.0, bake_loss_step=nan.0, zinb_loss_step=nan.0, mse_loss_epoch=nan.0, bake_loss_epoch=nan.0, zinb_loss_epoch=nan.0]loss: tensor(nan, device='cuda:0', grad_fn=<AddBackward0>)
> Epoch 1:  82%|████████▏ | 9/11 [00:01<00:00,  5.95it/s, v_num=29, mse_loss_step=nan.0, bake_loss_step=nan.0, zinb_loss_step=nan.0, mse_loss_epoch=nan.0, bake_loss_epoch=nan.0, zinb_loss_epoch=nan.0]loss: tensor(nan, device='cuda:0', grad_fn=<AddBackward0>)
> Epoch 1:  91%|█████████ | 10/11 [00:01<00:00,  6.01it/s, v_num=29, mse_loss_step=nan.0, bake_loss_step=nan.0, zinb_loss_step=nan.0, mse_loss_epoch=nan.0, bake_loss_epoch=nan.0, zinb_loss_epoch=nan.0]loss: tensor(nan, device='cuda:0', grad_fn=<AddBackward0>)
> Epoch 1: 100%|██████████| 11/11 [00:01<00:00,  5.56it/s, v_num=29, mse_loss_step=nan.0, bake_loss_step=nan.0, zinb_loss_step=nan.0, mse_loss_epoch=nan.0, bake_loss_epoch=nan.0, zinb_loss_epoch=nan.0]
> Validation: |          | 0/? [00:00<?, ?it/s]
> Validation:   0%|          | 0/1 [00:00<?, ?it/s]
> Validation DataLoader 0:   0%|          | 0/1 [00:00<?, ?it/s]Traceback (most recent call last):
>   File "/home/aaa/User/bbb/Hist2ST/HIST2ST_train.py", line 102, in <module>
>     trainer.fit(model, train_loader, test_loader)
>   File "/home/aaa/anaconda3/envs/hist2st/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 545, in fit
>     call._call_and_handle_interrupt(
>   File "/home/aaa/anaconda3/envs/hist2st/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 44, in _call_and_handle_interrupt
>     return trainer_fn(*args, **kwargs)
>   File "/home/aaa/anaconda3/envs/hist2st/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 581, in _fit_impl
>     self._run(model, ckpt_path=ckpt_path)
>   File "/home/aaa/anaconda3/envs/hist2st/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 990, in _run
>     results = self._run_stage()
>   File "/home/aaa/anaconda3/envs/hist2st/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1036, in _run_stage
>     self.fit_loop.run()
>   File "/home/aaa/anaconda3/envs/hist2st/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py", line 202, in run
>     self.advance()
>   File "/home/aaa/anaconda3/envs/hist2st/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py", line 359, in advance
>     self.epoch_loop.run(self._data_fetcher)
>   File "/home/aaa/anaconda3/envs/hist2st/lib/python3.9/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 137, in run
>     self.on_advance_end(data_fetcher)
>   File "/home/aaa/anaconda3/envs/hist2st/lib/python3.9/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 285, in on_advance_end
>     self.val_loop.run()
>   File "/home/aaa/anaconda3/envs/hist2st/lib/python3.9/site-packages/pytorch_lightning/loops/utilities.py", line 181, in _decorator
>     return loop_run(self, *args, **kwargs)
>   File "/home/aaa/anaconda3/envs/hist2st/lib/python3.9/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 134, in run
>     self._evaluation_step(batch, batch_idx, dataloader_idx, dataloader_iter)
>   File "/home/aaa/anaconda3/envs/hist2st/lib/python3.9/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 391, in _evaluation_step
>     output = call._call_strategy_hook(trainer, hook_name, *step_args)
>   File "/home/aaa/anaconda3/envs/hist2st/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 309, in _call_strategy_hook
>     output = fn(*args, **kwargs)
>   File "/home/aaa/anaconda3/envs/hist2st/lib/python3.9/site-packages/pytorch_lightning/strategies/strategy.py", line 403, in validation_step
>     return self.lightning_module.validation_step(*args, **kwargs)
>   File "/home/aaa/User/bbb/Hist2ST/HIST2ST.py", line 254, in validation_step
>     r.append(pearsonr(pred[g], exp[g])[0])
>   File "/home/aaa/anaconda3/envs/hist2st/lib/python3.9/site-packages/scipy/stats/_stats_py.py", line 4837, in pearsonr
>     normxm = linalg.norm(xm)
>   File "/home/aaa/anaconda3/envs/hist2st/lib/python3.9/site-packages/scipy/linalg/_misc.py", line 146, in norm
>     a = np.asarray_chkfinite(a)
>   File "/home/aaa/anaconda3/envs/hist2st/lib/python3.9/site-packages/numpy/lib/function_base.py", line 630, in asarray_chkfinite
>     raise ValueError(
> ValueError: array must not contain infs or NaNs
> Epoch 1: 100%|██████████| 11/11 [00:02<00:00,  4.33it/s, v_num=29, mse_loss_step=nan.0, bake_loss_step=nan.0, zinb_loss_step=nan.0, mse_loss_epoch=nan.0, bake_loss_epoch=nan.0, zinb_loss_epoch=nan.0]
> 
> 
> 进程已结束,退出代码1
> ```

Hi there, Have you solved this problem? I met the same problem in the cscc dataset with a new error:
  File "/home/hist2st/predict.py", line 46, in cluster
    l=label[idx]

TypeError: 'NoneType' object is not subscriptable

Could you please let me know if you have solved this problem? Many thanks!
